### ISSUE TITLE
Continuous integration via Travis

### ISSUE THREAD

**Issue by netzwerg** [fhnw-stec/stec#2]

**Comment by netzwerg** [comment]
Currently our [build is failing](https://travis-ci.org/fhnw-stec/stec/builds/245405880) because travis hits the GitHub REST API [rate limit](https://developer.github.com/v3/#rate-limiting).

@markus-d: Would you be interested in looking into this?

**Comment by markus-d** [comment]
According to: https://www.tomsdev.com/blog/2015/tsd-travis-ci-github-rate-limit-reached/ it seems quite easy to do - only problem is, that I have not found a way yet to generate a non personal access token (Which is not tied to my personal git account) - have to dig in deeper.

**Comment by netzwerg** [comment]
Probably it would need to be a personal token for **my account** (since Travis is linked to my account).

However, the blog post you linked specifically solves this problem for TSD (the deprecated typescript repo). We would need something similar, but also would need to figure out how to wire the env variable to the fetch calls in our code.

Maybe we should just wait and see how many failing builds we actually get...

**Comment by netzwerg** [comment]
Done (excluding integration tests on Travis).
